---
name: ci
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  cdk:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - "12.x"
          - "14.x"
          - "15.x"
    steps:
      - name: Get yarn cache
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - uses: actions/checkout@v1
      - uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-node${{ matrix.node }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-node${{ matrix.node }}
      -
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - name: install
        run: yarn install --frozen-lockfile
      - name: test
        run: yarn test
      - name: lint
        uses: reviewdog/action-eslint@v1.1.2
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          eslint_flags: '--ext .ts src/'
